Bugfix/unitless gutter on masonry column
peterramsing/lost pull request #384
Opened 2017-07-01 18:11 UTC by peterramsing

**What kind of change is this? (Bug Fix, Feature...)**
🐞

**What is the current behavior (You can also link to an issue)**
#383

**What is the new behavior this introduces (if any)**

**Does this introduce any breaking changes?**
Shouldn't

**Does the PR fulfill these requirements?**
- [x] Tests for the changes have been added
- [N/A] Docs have been added or updated

2017-07-01 18:24 UTC, peterramsing commented
I'm fixing up a bunch of the code in here while I'm here. Noticed there were a few dead lines and more test coverage needs. I have on more thing to check after this commit but I need to head home from the coffee shop. I think that `ln27` is a dead line but I'm not sure.

2017-07-02 04:11 UTC, peterramsing commented
This should be good to go, now.

2017-07-13 13:36 UTC, peterramsing commented
@codebysubtract If you want to glance at this and make sure I'm not crazy we can get this in. 👍

2017-07-14 07:05 UTC, steve-holland requested changes
Looking good overall. Just a minor thing in the tests, which may come down to personal preference, so I won't mind if you disagree :)

2017-07-14 07:05 UTC, codebysubtract commented on test/lost-masonry-column.js
> +    it('supports a null unit for "no gutter"', function() {
I'm not sure you need a separate test here. I think you could add the `check` done here to the test above `supports no gutter`. You are essentially checking the same thing, just whether they have added the unit to the end or not. Only very minor thing, so by no means essential.

2017-07-16 17:11 UTC, peterramsing commented
@codebysubtract Thanks! Yeah, those could certainly be merged together. Done. Gonna merge. 👍

2017-07-16 17:11 UTC, merged