Adds new lost-vars functionality.
peterramsing/lost pull request #389
Opened 2017-07-11 14:20 UTC by codebysubtract

**What kind of change is this? (Bug Fix, Feature...)**
Feature.

**What is the current behavior (You can also link to an issue)**
Solves #376. Future replacement for `$lost-gutter` and `$lost-gutter-local` variables.

**What is the new behavior this introduces (if any)**
New `lost-vars` method to output variables.

**Does this introduce any breaking changes?**
No.

**Does the PR fulfill these requirements?**
- [✔️ ] Tests for the changes have been added
- [✔️ ] Docs have been added or updated

**Other Comments**
I've updated `lg-gutter` so that it shares same functionality as new `lost-vars` method, save duplicating code. Only thing I'm not sure you'll like is how I've broken out each of the new variable methods into its own file. See what you think, I can always change it if you aren't keen.

2017-07-12 03:07 UTC, peterramsing requested changes
Gah! I'm in love with this code!
1. Brilliant how you have `lgGutter` extend the logic of this!
2. The `lost-vars()` logic is really nice. It'll be really nice to expand on!
3. There looks like possible duplicate tests. (see comment)
4. It'd be nice to have a test for both `gutter` and `gutter-local` in one declaration. (see comment)
5. Do we want to add a warning to the existing `lgLogic` implementation since we're planning on deprecating it in the future?

---
That's all I can think of right now. This is awesome stuff!

2017-07-12 03:07 UTC, peterramsing commented on test/lost-vars.js
> +      check(
Is this a duplicate of the test on `ln15`?

2017-07-12 03:07 UTC, peterramsing commented on test/lost-vars.js
> +  it('matches multiple variables', function() {
It might also be good to have a test for the use of both the `lost-vars('gutter')` and `lost-vars('gutter-local')` in one declaration.

2017-07-12 03:07 UTC, peterramsing commented on lib/lost-vars.js
> +  'gutter-local': lostGutterLocal
A hanging comma on this would help with future diffs.

2017-07-12 03:07 UTC, peterramsing commented on lib/lost-vars.js
> +      var func = variableFunctions[variable];
I'm in love with this code!

2017-07-12 06:45 UTC, codebysubtract commented on test/lost-vars.js
> +      check(
It is, great minds again! I'd already done one of my own and then repurposed your tests, which already had one. I've removed this one as it was specific to just `gutter-local`. Whereas the other one covers both.

2017-07-12 06:47 UTC, codebysubtract commented on lib/lost-vars.js
> +  'gutter-local': lostGutterLocal
Updated.

2017-07-12 06:47 UTC, codebysubtract commented on lib/lost-vars.js
> +      var func = variableFunctions[variable];
Thanks, I'm really enjoying working on Lost :)

2017-07-12 06:50 UTC, codebysubtract commented on test/lost-vars.js
> +  it('matches multiple variables', function() {
I've updated this test to include a new `check` which does just that.

2017-07-12 06:50 UTC, equinusocio commented
What version will include this feature?

2017-07-13 13:36 UTC, peterramsing approved these changes

2017-07-13 13:38 UTC, peterramsing commented
At this point, since it's done I don't see why it has to wait for 8.3. I'm the holdup on 8.2 and getting the test coverage up #381. 😳

2017-07-16 17:13 UTC, merged