fix(plugin): fix options assignment
peterramsing/lost pull request #453
Opened 2022-06-28 09:21 UTC by ThornWalli

Hello @peterramsing,

still have a problem applying the user setting via an options object.

Here is a `Bitwise OR` used 😉 (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_OR)
```
 let runSettings = assign({}, defaultSettings, settings | {});
```

But we need a `Logical OR` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR)

```
 let runSettings = assign({}, defaultSettings, settings || {});
```

Thanks!

2022-06-28 23:20 UTC, peterramsing commented
Well shucks. I'm glad I got pulled away and forgot to release that night. Would be worth writing some tests for this.

2022-06-28 23:20 UTC, peterramsing commented
PS: Thank you for the help!

2022-06-28 23:23 UTC, peterramsing commented
Current tests are running - then either you're welcome to get a test that fails without this code so we can make sure we don't regress *or* I'll snag some time to do it. I've added a flag to this on my OmniFocus project so it's surfaced better for me.

2022-06-29 07:28 UTC, ThornWalli commented
Created a test :)

2022-06-30 04:58 UTC, peterramsing requested changes
One tiny nit to make the tests more readable if they fail.

Thanks for doing this!

2022-06-30 04:58 UTC, peterramsing commented on test/lost-plugin-options.js
> +      expect(output).to.equal(result.css);
```suggestion
      expect(result.css).to.equal(output);
```
It's minor, but this reads better when reading errors.

What it should read like when this test fails:
<img width="435" alt="Screen Shot 2022-06-29 at 21 56 23" src="https://user-images.githubusercontent.com/3523268/176595954-57e7f909-b087-467c-810b-d3b4695d15d6.png">

2022-06-30 05:03 UTC, peterramsing commented
doh - listing rules are failing the CI. 👀

2022-06-30 05:07 UTC, peterramsing commented
...I want to look at this further but I have to get some sleep. I have some time tomorrow slated to look at this. Not sure if I want to change the eslint or adapt the test. Also, it looks like the coverage drops on `lost.js` on `ln50` so that needs a quick glance. Not sure how that happened. 🤔

2022-06-30 20:19 UTC, peterramsing commented
@ThornWalli, if you pull the latest from `master` the tests should pass.

---

I'm not sure why the coverage fell a bit. Gonna poke on that a bit more.

2022-06-30 22:28 UTC, peterramsing commented
Weird - coverage didn't change, now. <shakes fist at computer>
--
Looks good to me! Thanks!

2022-06-30 22:29 UTC, merged